
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en' | 'zh' | 'fr' | 'de' | 'es' | 'nl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
  fontFamily: string;
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    home: 'الرئيسية',
    destinations: 'الوجهات',
    searchPlaceholder: 'ابحث عن دولة...',
    searchHeroPlaceholder: 'إلى أين تريد السفر اليوم؟',
    discoverWorld: 'اكتشف العالم بلمسة المستقبل',
    heroSubtitle: 'دليلك الذكي لكل مغامرة ورحلة استكشاف حول العالم',
    featuredDestinations: 'وجهات العالم',
    exploreGuide: 'استكشف الدليل الشامل',
    otherDestinations: 'وجهات أخرى...',
    useSearch: 'استخدم البحث للوصول لأي مكان',
    about: 'عن الوجهة',
    bestTime: 'أفضل وقت للزيارة',
    tips: 'نصائح للمسافرين',
    save: 'حفظ',
    share: 'مشاركة',
    landmarks: 'المعالم السياحية',
    landmarkDesc: 'استكشف أهم الأماكن التي يوصى بزيارتها',
    readMore: 'اقرأ التفاصيل الكاملة',
    story: 'قصة المكان',
    whyVisit: 'لماذا تزوره؟',
    visitorTips: 'نصائح للزوار',
    addToFavorites: 'احفظ في مفضلاتي',
    footerDesc: 'بوابتك المستقبلية لاكتشاف عجائب العالم. نحن نجمع بين التاريخ العريق والتكنولوجيا الحديثة لنقدم لك تجربة سفر لا تنسى.',
    quickLinks: 'روابط سريعة',
    contactUs: 'تواصل معنا',
    rightsReserved: 'جميع الحقوق محفوظة',
    loading: 'جاري تحضير الدليل السياحي الذكي...',
    loadingSub: 'نستجمع المعلومات ونكتب القصص لأجلك',
    error: 'عذراً',
    errorMsg: 'لم نتمكن من جلب المعلومات',
    backHome: 'عودة للرئيسية',
    pyramid: 'الهرم',
    restaurants: 'أفضل المطاعم',
    restaurantsDesc: 'تذوق أشهى المأكولات في أرقى الأماكن',
    cuisine: 'المطبخ',
    rating: 'التقييم',
    hotels: 'أفضل الفنادق',
    hotelsDesc: 'إقامة فاخرة ومريحة في أفضل الأماكن',
    stars: 'نجوم',
    perNight: 'في الليلة',
    bookNow: 'احجز الآن',
    viewOnEarth: 'مشاهدة على Google Earth',
    askOracle: 'اسأل العراف',
    oraclePlaceholder: 'اسألني عن هذه الوجهة...',
    oracleWelcome: 'أنا العراف، دليلك الذكي. أنا هنا للإجابة عن أي سؤال يخص رحلتك.',
    listening: 'جاري السرد...',
    listenStory: 'استمع للقصة',
    stopStory: 'إيقاف السرد',
    back: 'رجوع',
    region_ArabWorld: 'الدول العربية',
    region_Europe: 'أوروبا',
    region_Asia: 'آسيا',
    region_Americas: 'الأمريكتين',
    region_Africa: 'أفريقيا',
    region_Oceania: 'أوقيانوسيا',
    cat_History: 'تاريخ',
    cat_Nature: 'طبيعة',
    cat_Modern: 'حديث',
    cat_HiddenGem: 'جوهرة خفية',
    sound_atmosphere: 'أجواء',
    sound_off: 'كتم الصوت',
    sound_start: 'تشغيل الأجواء',
    homeCardGenericDesc: 'استكشف الدليل الشامل والتفاصيل الساحرة عن {country}.',
  },
  en: {
    home: 'Home',
    destinations: 'Destinations',
    searchPlaceholder: 'Search for a country...',
    searchHeroPlaceholder: 'Where do you want to travel today?',
    discoverWorld: 'Discover the world with a futuristic touch',
    heroSubtitle: 'Your smart guide for every adventure and discovery around the world',
    featuredDestinations: 'Global Destinations',
    exploreGuide: 'Explore Full Guide',
    otherDestinations: 'Other Destinations...',
    useSearch: 'Use search to find any place',
    about: 'About',
    bestTime: 'Best Time to Visit',
    tips: 'Traveler Tips',
    save: 'Save',
    share: 'Share',
    landmarks: 'Landmarks',
    landmarkDesc: 'Explore top recommended places to visit',
    readMore: 'Read Full Details',
    story: 'The Story',
    whyVisit: 'Why Visit?',
    visitorTips: 'Visitor Tips',
    addToFavorites: 'Add to Favorites',
    footerDesc: 'Your futuristic gateway to discovering world wonders. We combine ancient history with modern technology for an unforgettable travel experience.',
    quickLinks: 'Quick Links',
    contactUs: 'Contact Us',
    rightsReserved: 'All rights reserved',
    loading: 'Preparing your smart travel guide...',
    loadingSub: 'Gathering information and writing stories for you',
    error: 'Sorry',
    errorMsg: 'Could not fetch information',
    backHome: 'Back to Home',
    pyramid: 'PYRAMID',
    restaurants: 'Top Restaurants',
    restaurantsDesc: 'Taste the finest cuisine in top-rated places',
    cuisine: 'Cuisine',
    rating: 'Rating',
    hotels: 'Top Hotels',
    hotelsDesc: 'Luxury and comfortable stays in the best locations',
    stars: 'Stars',
    perNight: 'per night',
    bookNow: 'Book Now',
    viewOnEarth: 'View on Google Earth',
    askOracle: 'Ask The Oracle',
    oraclePlaceholder: 'Ask me about this destination...',
    oracleWelcome: 'I am The Oracle, your smart guide. I am here to answer any question about your trip.',
    listening: 'Narrating...',
    listenStory: 'Listen to Story',
    stopStory: 'Stop Narration',
    back: 'Back',
    region_ArabWorld: 'Arab World',
    region_Europe: 'Europe',
    region_Asia: 'Asia',
    region_Americas: 'Americas',
    region_Africa: 'Africa',
    region_Oceania: 'Oceania',
    cat_History: 'History',
    cat_Nature: 'Nature',
    cat_Modern: 'Modern',
    cat_HiddenGem: 'Hidden Gem',
    sound_atmosphere: 'Atmosphere',
    sound_off: 'Sound Off',
    sound_start: 'Start Atmosphere',
    homeCardGenericDesc: 'Explore the comprehensive guide and enchanting details about {country}.',
  },
  zh: {
    home: '主页',
    destinations: '目的地',
    searchPlaceholder: '搜索国家...',
    searchHeroPlaceholder: '今天你想去哪里旅行？',
    discoverWorld: '以未来感触碰探索世界',
    heroSubtitle: '故事，历史和难忘的地方',
    featuredDestinations: '全球目的地',
    exploreGuide: '探索完整指南',
    otherDestinations: '其他目的地...',
    useSearch: '使用搜索查找任何地方',
    about: '关于',
    bestTime: '最佳旅游时间',
    tips: '旅行者贴士',
    save: '保存',
    share: '分享',
    landmarks: '地标',
    landmarkDesc: '探索推荐的必游之地',
    readMore: '阅读完整详情',
    story: '故事',
    whyVisit: '为什么要参观？',
    visitorTips: '游客贴士',
    addToFavorites: '添加到收藏夹',
    footerDesc: '您探索世界奇观的未来门户。我们将古老的历史与现代技术相结合，为您带来难忘的旅行体验。',
    quickLinks: '快速链接',
    contactUs: '联系我们',
    rightsReserved: '版权所有',
    loading: '正在准备您的智能旅行指南...',
    loadingSub: '为您收集信息并撰写故事',
    error: '抱歉',
    errorMsg: '无法获取信息',
    backHome: '返回主页',
    pyramid: '金字塔',
    restaurants: '顶级餐厅',
    restaurantsDesc: '在顶级场所品尝最美味的佳肴',
    cuisine: '美食',
    rating: '评分',
    hotels: '顶级酒店',
    hotelsDesc: '最佳地点的豪华舒适住宿',
    stars: '星级',
    perNight: '每晚',
    bookNow: '立即预订',
    viewOnEarth: '在 Google 地球上查看',
    askOracle: '询问神谕',
    oraclePlaceholder: '询问关于这个目的地...',
    oracleWelcome: '我是神谕，您的智能向导。我在这里回答您关于旅行的任何问题。',
    listening: '正在叙述...',
    listenStory: '听故事',
    stopStory: '停止叙述',
    back: '返回',
    region_ArabWorld: '阿拉伯世界',
    region_Europe: '欧洲',
    region_Asia: '亚洲',
    region_Americas: '美洲',
    region_Africa: '非洲',
    region_Oceania: '大洋洲',
    cat_History: '历史',
    cat_Nature: '自然',
    cat_Modern: '现代',
    cat_HiddenGem: '隐藏的宝石',
    sound_atmosphere: '氛围',
    sound_off: '静音',
    sound_start: '开启氛围',
    homeCardGenericDesc: '探索关于 {country} 的综合指南和迷人细节。',
  },
  fr: {
    home: 'Accueil',
    destinations: 'Destinations',
    searchPlaceholder: 'Rechercher un pays...',
    searchHeroPlaceholder: 'Où voulez-vous voyager aujourd\'hui ?',
    discoverWorld: 'Découvrez le monde avec une touche futuriste',
    heroSubtitle: 'Histoires, histoire et lieux inoubliables',
    featuredDestinations: 'Destinations Mondiales',
    exploreGuide: 'Explorer le guide complet',
    otherDestinations: 'Autres destinations...',
    useSearch: 'Utilisez la recherche pour trouver n\'importe quel lieu',
    about: 'À propos',
    bestTime: 'Meilleur moment pour visiter',
    tips: 'Conseils aux voyageurs',
    save: 'Enregistrer',
    share: 'Partager',
    landmarks: 'Monuments',
    landmarkDesc: 'Découvrez les lieux recommandés à visiter',
    readMore: 'Lire tous les détails',
    story: 'L\'Histoire',
    whyVisit: 'Pourquoi visiter ?',
    visitorTips: 'Conseils aux visiteurs',
    addToFavorites: 'Ajouter aux favoris',
    footerDesc: 'Votre passerelle futuriste pour découvrir les merveilles du monde. Nous combinons l\'histoire ancienne et la technologie moderne.',
    quickLinks: 'Liens rapides',
    contactUs: 'Contactez-nous',
    rightsReserved: 'Tous droits réservés',
    loading: 'Préparation de votre guide de voyage intelligent...',
    loadingSub: 'Collecte d\'informations et rédaction d\'histoires pour vous',
    error: 'Désolé',
    errorMsg: 'Impossible de récupérer les informations',
    backHome: 'Retour à l\'accueil',
    pyramid: 'PYRAMIDE',
    restaurants: 'Meilleurs Restaurants',
    restaurantsDesc: 'Goûtez à la meilleure cuisine dans des lieux haut de gamme',
    cuisine: 'Cuisine',
    rating: 'Évaluation',
    hotels: 'Meilleurs Hôtels',
    hotelsDesc: 'Séjours luxueux et confortables',
    stars: 'Étoiles',
    perNight: 'par nuit',
    bookNow: 'Réserver',
    viewOnEarth: 'Voir sur Google Earth',
    askOracle: 'Demander à l\'Oracle',
    oraclePlaceholder: 'Posez-moi des questions sur cette destination...',
    oracleWelcome: 'Je suis l\'Oracle, votre guide intelligent. Je suis là pour répondre à toutes vos questions.',
    listening: 'Narration...',
    listenStory: 'Écouter l\'histoire',
    stopStory: 'Arrêter la narration',
    back: 'Retour',
    region_ArabWorld: 'Monde Arabe',
    region_Europe: 'Europe',
    region_Asia: 'Asie',
    region_Americas: 'Amériques',
    region_Africa: 'Afrique',
    region_Oceania: 'Océanie',
    cat_History: 'Histoire',
    cat_Nature: 'Nature',
    cat_Modern: 'Moderne',
    cat_HiddenGem: 'Joyau Caché',
    sound_atmosphere: 'Atmosphère',
    sound_off: 'Son Désactivé',
    sound_start: 'Démarrer l\'Atmosphère',
    homeCardGenericDesc: 'Explorez le guide complet et les détails enchanteurs sur {country}.',
  },
  de: {
    home: 'Startseite',
    destinations: 'Reiseziele',
    searchPlaceholder: 'Suche nach einem Land...',
    searchHeroPlaceholder: 'Wohin möchten Sie heute reisen?',
    discoverWorld: 'Entdecken Sie die Welt mit einem futuristischen Touch',
    heroSubtitle: 'Geschichten, Geschichte und unvergessliche Orte',
    featuredDestinations: 'Weltweite Reiseziele',
    exploreGuide: 'Vollständigen Reiseführer erkunden',
    otherDestinations: 'Andere Reiseziele...',
    useSearch: 'Nutzen Sie die Suche, um jeden Ort zu finden',
    about: 'Über',
    bestTime: 'Beste Reisezeit',
    tips: 'Reisetipps',
    save: 'Speichern',
    share: 'Teilen',
    landmarks: 'Sehenswürdigkeiten',
    landmarkDesc: 'Erkunden Sie die besten empfohlenen Orte',
    readMore: 'Vollständige Details lesen',
    story: 'Die Geschichte',
    whyVisit: 'Warum besuchen?',
    visitorTips: 'Besuchertipps',
    addToFavorites: 'Zu Favoriten hinzufügen',
    footerDesc: 'Ihr futuristisches Tor zur Entdeckung von Weltwundern. Wir verbinden alte Geschichte mit moderner Technologie.',
    quickLinks: 'Schnelllinks',
    contactUs: 'Kontaktieren Sie uns',
    rightsReserved: 'Alle Rechte vorbehalten',
    loading: 'Ihr smarter Reiseführer wird vorbereitet...',
    loadingSub: 'Informationen sammeln und Geschichten für Sie schreiben',
    error: 'Entschuldigung',
    errorMsg: 'Informationen konnten nicht abgerufen werden',
    backHome: 'Zurück zur Startseite',
    pyramid: 'PYRAMIDE',
    restaurants: 'Top-Restaurants',
    restaurantsDesc: 'Probieren Sie die feinste Küche an erstklassigen Orten',
    cuisine: 'Küche',
    rating: 'Bewertung',
    hotels: 'Top-Hotels',
    hotelsDesc: 'Luxuriöse und komfortable Aufenthalte',
    stars: 'Sterne',
    perNight: 'pro Nacht',
    bookNow: 'Jetzt buchen',
    viewOnEarth: 'Auf Google Earth ansehen',
    askOracle: 'Frag das Orakel',
    oraclePlaceholder: 'Frag mich nach diesem Reiseziel...',
    oracleWelcome: 'Ich bin das Orakel, dein smarter Guide. Ich bin hier, um deine Fragen zu beantworten.',
    listening: 'Erzählen...',
    listenStory: 'Geschichte anhören',
    stopStory: 'Erzählung stoppen',
    back: 'Zurück',
    region_ArabWorld: 'Arabische Welt',
    region_Europe: 'Europa',
    region_Asia: 'Asien',
    region_Americas: 'Amerika',
    region_Africa: 'Afrika',
    region_Oceania: 'Ozeanien',
    cat_History: 'Geschichte',
    cat_Nature: 'Natur',
    cat_Modern: 'Modern',
    cat_HiddenGem: 'Geheimtipp',
    sound_atmosphere: 'Atmosphäre',
    sound_off: 'Ton Aus',
    sound_start: 'Atmosphäre Starten',
    homeCardGenericDesc: 'Erkunden Sie den umfassenden Reiseführer und bezaubernde Details über {country}.',
  },
  es: {
    home: 'Inicio',
    destinations: 'Destinos',
    searchPlaceholder: 'Buscar un país...',
    searchHeroPlaceholder: '¿A dónde querés viajar hoy?',
    discoverWorld: 'Descubrí el mundo con un toque futurista',
    heroSubtitle: 'Historias, historia y lugares inolvidables',
    featuredDestinations: 'Destinos Globales',
    exploreGuide: 'Explorar Guía Completa',
    otherDestinations: 'Otros Destinos...',
    useSearch: 'Usá la búsqueda para encontrar cualquier lugar',
    about: 'Acerca de',
    bestTime: 'Mejor época para visitar',
    tips: 'Consejos para viajeros',
    save: 'Guardar',
    share: 'Compartir',
    landmarks: 'Puntos de Interés',
    landmarkDesc: 'Explorá los lugares más recomendados para visitar',
    readMore: 'Leer todos los detalles',
    story: 'La Historia',
    whyVisit: '¿Por qué visitar?',
    visitorTips: 'Consejos para visitantes',
    addToFavorites: 'Agregar a Favoritos',
    footerDesc: 'Tu puerta futurista para descubrir las maravillas del mundo. Combinamos historia antigua con tecnología moderna para una experiencia de viaje inolvidable.',
    quickLinks: 'Enlaces Rápidos',
    contactUs: 'Contactanos',
    rightsReserved: 'Todos los derechos reservados',
    loading: 'Preparando tu guía de viaje inteligente...',
    loadingSub: 'Recopilando información y escribiendo historias para vos',
    error: 'Lo siento',
    errorMsg: 'No se pudo obtener la información',
    backHome: 'Volver al Inicio',
    pyramid: 'PIRÁMIDE',
    restaurants: 'Mejores Restaurantes',
    restaurantsDesc: 'Probá la mejor cocina en lugares de primera categoría',
    cuisine: 'Cocina',
    rating: 'Calificación',
    hotels: 'Mejores Hoteles',
    hotelsDesc: 'Estadías lujosas y cómodas en las mejores ubicaciones',
    stars: 'Estrellas',
    perNight: 'por noche',
    bookNow: 'Reservar Ahora',
    viewOnEarth: 'Ver en Google Earth',
    askOracle: 'Preguntale al Oráculo',
    oraclePlaceholder: 'Preguntame sobre este destino...',
    oracleWelcome: 'Soy el Oráculo, tu guía inteligente. Estoy acá para responder cualquier pregunta sobre tu viaje.',
    listening: 'Narrando...',
    listenStory: 'Escuchar Historia',
    stopStory: 'Detener Narración',
    back: 'Volver',
    region_ArabWorld: 'Mundo Árabe',
    region_Europe: 'Europa',
    region_Asia: 'Asia',
    region_Americas: 'Américas',
    region_Africa: 'África',
    region_Oceania: 'Oceanía',
    cat_History: 'Historia',
    cat_Nature: 'Naturaleza',
    cat_Modern: 'Moderno',
    cat_HiddenGem: 'Joya Oculta',
    sound_atmosphere: 'Atmósfera',
    sound_off: 'Silencio',
    sound_start: 'Iniciar Atmósfera',
    homeCardGenericDesc: 'Explorá la guía completa y los detalles encantadores sobre {country}.',
  },
  nl: {
    home: 'Home',
    destinations: 'Bestemmingen',
    searchPlaceholder: 'Zoek een land...',
    searchHeroPlaceholder: 'Waar wil je vandaag naartoe reizen?',
    discoverWorld: 'Ontdek de wereld met een futuristisch tintje',
    heroSubtitle: 'Verhalen, geschiedenis en onvergetelijke plekken',
    featuredDestinations: 'Wereldwijde Bestemmingen',
    exploreGuide: 'Verken Volledige Gids',
    otherDestinations: 'Andere Bestemmingen...',
    useSearch: 'Gebruik de zoekfunctie om elke plek te vinden',
    about: 'Over',
    bestTime: 'Beste reistijd',
    tips: 'Reizigerstips',
    save: 'Opslaan',
    share: 'Delen',
    landmarks: 'Bezienswaardigheden',
    landmarkDesc: 'Verken de beste aanbevolen plekken om te bezoeken',
    readMore: 'Lees volledige details',
    story: 'Het Verhaal',
    whyVisit: 'Waarom bezoeken?',
    visitorTips: 'Bezoekerstips',
    addToFavorites: 'Toevoegen aan Favorieten',
    footerDesc: 'Jouw futuristische toegangspoort tot het ontdekken van wereldwonderen. We combineren oude geschiedenis met moderne technologie voor een onvergetelijke reiservaring.',
    quickLinks: 'Snelle Links',
    contactUs: 'Neem Contact Op',
    rightsReserved: 'Alle rechten voorbehouden',
    loading: 'Je slimme reisgids voorbereiden...',
    loadingSub: 'Informatie verzamelen en verhalen voor je schrijven',
    error: 'Sorry',
    errorMsg: 'Kon informatie niet ophalen',
    backHome: 'Terug naar Home',
    pyramid: 'PIRAMIDE',
    restaurants: 'Toprestaurants',
    restaurantsDesc: 'Proef de fijnste gerechten op toplocaties',
    cuisine: 'Keuken',
    rating: 'Beoordeling',
    hotels: 'Tophotels',
    hotelsDesc: 'Luxe en comfortabele verblijven op de beste locaties',
    stars: 'Sterren',
    perNight: 'per nacht',
    bookNow: 'Boek Nu',
    viewOnEarth: 'Bekijk op Google Earth',
    askOracle: 'Vraag het Orakel',
    oraclePlaceholder: 'Vraag me over deze bestemming...',
    oracleWelcome: 'Ik ben het Orakel, je slimme gids. Ik ben hier om elke vraag over je reis te beantwoorden.',
    listening: 'Vertellen...',
    listenStory: 'Luister naar Verhaal',
    stopStory: 'Stop Vertelling',
    back: 'Terug',
    region_ArabWorld: 'Arabische Wereld',
    region_Europe: 'Europa',
    region_Asia: 'Azië',
    region_Americas: 'Amerika',
    region_Africa: 'Afrika',
    region_Oceania: 'Oceanië',
    cat_History: 'Geschiedenis',
    cat_Nature: 'Natuur',
    cat_Modern: 'Modern',
    cat_HiddenGem: 'Verborgen Parel',
    sound_atmosphere: 'Sfeer',
    sound_off: 'Geluid Uit',
    sound_start: 'Start Sfeer',
    homeCardGenericDesc: 'Verken de uitgebreide gids en betoverende details over {country}.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ar');

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  const getFontFamily = () => {
    switch (language) {
      case 'ar': return 'font-cairo';
      case 'zh': return 'font-chinese';
      default: return 'font-sans';
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir, fontFamily: getFontFamily() }}>
      <div className={`${getFontFamily()} ${dir === 'rtl' ? 'text-right' : 'text-left'}`}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};